### ISSUE TITLE
Sample fails to function

### ISSUE THREAD

**Issue by andyrj** [wallabyjs/wallaby-webpack-sample#3]
I am trying to evaluate Wallaby.js, I use VS code and webpack...  I do the following to replicate non-functional vs code integration with this project.

1) git clone project
2) npm install
3) open project directory with vs code
4) Ctrl + Shift + R, r
5) ...  expecting source code for Person.js to be tested and have markers on editor, but nothing shows up

I have tried restarting Wallaby, restarting vs code, this doesn't seem to help.  I also tried installing webpack globally instead of just local in npm but no change...

Would really like to use this product but at this point I can't get it to work with webpack at all in my own projects or with your sample

**Comment by ArtemGovorov** [comment]
I'll address this issue in the main repo: https://github.com/wallabyjs/public/issues/883
